import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('.', import.meta.url)),
    },
  },
  test: {
    environment: 'jsdom',
    pool: 'threads',
    environmentOptions: {
      jsdom: {
        url: 'https://www.zhipin.com/web/geek/job',
      },
    },
    globals: true,
    setupFiles: ['./tests/setup.ts'],
    include: ['**/*.test.{ts,tsx}'],
    exclude: [
      'node_modules/**',
      '.output/**',
      '.wxt/**',
      '.reference/**',
      'coverage/**',
      'design-prototype/**',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'html'],
      reportsDirectory: 'coverage',
      include: [
        'lib/adapter/city-codes.ts',
        'lib/adapter/zhipin.ts',
        'lib/attachments/input.ts',
        'lib/browser/semantic-search.ts',
        'lib/browser/resource-lock.ts',
        'lib/browser/tab-router.ts',
        'lib/browser/visual-page.ts',
        'lib/diagnostics/recorder.ts',
        'lib/diagnostics/page-structure.ts',
        'lib/diagnostics/redaction.ts',
        'lib/diagnostics/report.ts',
        'lib/domain/chat.ts',
        'lib/evals/health.ts',
        'lib/evals/run-summary.ts',
        'lib/generation/conversation-title.ts',
        'lib/generation/compaction.ts',
        'lib/generation/errors.ts',
        'lib/generation/manager.ts',
        'lib/generation/pi-adapter.ts',
        'lib/generation/resolve.ts',
        'lib/generation/registry.ts',
        'lib/ipc/protocol.ts',
        'lib/llm/client.ts',
        'lib/memory/store.ts',
        'lib/memory/prompt.ts',
        'lib/memory/client.ts',
        'lib/mcp/store.ts',
        'lib/mcp/service.ts',
        'lib/mcp/client.ts',
        'lib/mcp/official-client.ts',
        'lib/skills/parser.ts',
        'lib/skills/host-bridge.ts',
        'lib/skills/package.ts',
        'lib/skills/sandbox.ts',
        'lib/skills/builtin.ts',
        'lib/skills/store.ts',
        'lib/skills/prompt.ts',
        'lib/skills/client.ts',
        'lib/providers/client.ts',
        'lib/providers/discovery.ts',
        'lib/providers/permissions.ts',
        'lib/providers/registry.ts',
        'lib/providers/service.ts',
        'lib/providers/store.ts',
        'lib/page/access.ts',
        'lib/page/extractor.ts',
        'lib/page/pending.ts',
        'lib/page/snapshot.ts',
        'lib/portability/backup.ts',
        'lib/storage/access.ts',
        'lib/storage/config.ts',
        'lib/storage/db.ts',
        'lib/tools/read-current-page.ts',
        'lib/tools/ask-user.ts',
        'lib/tools/read-current-job.ts',
        'lib/tools/read-visible-jobs.ts',
        'lib/tools/browser-action.ts',
        'lib/tools/tab.ts',
        'lib/tools/load-skill.ts',
        'lib/tools/run-skill.ts',
        'lib/tools/memory.ts',
        'lib/tools/page-interaction.ts',
        'lib/tools/workspace.ts',
        'lib/workspace/path.ts',
        'lib/workspace/storage.ts',
        'entrypoints/sidepanel/ChatFlowStatus.tsx',
        'entrypoints/sidepanel/AskUserPanel.tsx',
        'entrypoints/sidepanel/HistoryView.tsx',
        'entrypoints/sidepanel/SettingsView.tsx',
        'entrypoints/sidepanel/SkillSettings.tsx',
        'entrypoints/sidepanel/SkillEditor.tsx',
        'entrypoints/sidepanel/SkillReference.ts',
        'entrypoints/sidepanel/AgentContextSettings.tsx',
        'entrypoints/sidepanel/McpSettings.tsx',
        'entrypoints/sidepanel/AgentHealthCheck.tsx',
        'entrypoints/sidepanel/DataPortability.tsx',
        'entrypoints/sidepanel/usePort.ts',
      ],
      thresholds: {
        statements: 95,
        branches: 89,
        functions: 95,
        lines: 97,
      },
    },
  },
});
